#!/bin/sh

./distclean
perl Makefile.PL skipme && make dist
if [ -d ~/www/PerlModules ]; then
    cp Bu*gz ~/www/PerlModules
    cat CSI.pm | pod2html > ~/www/PerlModules/CSI.html
    rm -vf pod*
    echo don\'t forget to fix the content.html 
fi
mv Bu*gz ../archives
